-- ============================================================
-- Speak&Go Evolution Method — Prioridade 1
-- Novas tabelas: ciclos (Evolution Plan) e feedbacks (nível percebido)
-- NÃO altera tabelas existentes. Segue o padrão de RLS do projeto.
-- Obs.: students.id é BIGINT no banco ao vivo (as migrations antigas
-- diziam UUID, mas o schema real usa bigint identity).
-- ============================================================

-- ---------- Tabela: ciclos (Evolution Plan) ----------
CREATE TABLE IF NOT EXISTS public.ciclos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  objetivo TEXT,
  semana_atual INTEGER NOT NULL DEFAULT 1 CHECK (semana_atual BETWEEN 1 AND 8),
  habilidades_prioritarias TEXT[] NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'concluido', 'renovado')),
  -- Campos editáveis do Guia de Progresso (o resto é composto de Feedback/Aula)
  proximo_foco TEXT,
  checkpoint_date DATE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.ciclos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own ciclos or admins can view all"
ON public.ciclos FOR SELECT TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can create their own ciclos or admins can create any"
ON public.ciclos FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can update their own ciclos or admins can update any"
ON public.ciclos FOR UPDATE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can delete their own ciclos or admins can delete any"
ON public.ciclos FOR DELETE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER update_ciclos_updated_at
  BEFORE UPDATE ON public.ciclos
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_ciclos_student_id ON public.ciclos(student_id);
CREATE INDEX IF NOT EXISTS idx_ciclos_user_id ON public.ciclos(user_id);
CREATE INDEX IF NOT EXISTS idx_ciclos_status ON public.ciclos(status);

-- ---------- Tabela: feedbacks (nível percebido) ----------
-- Escala qualitativa (não numérica): comecando / em_construcao / confortavel / confiante
CREATE TABLE IF NOT EXISTS public.feedbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  ciclo_id BIGINT REFERENCES public.ciclos(id) ON DELETE SET NULL,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  observacao TEXT,
  data DATE NOT NULL DEFAULT CURRENT_DATE,
  nivel_speaking TEXT CHECK (nivel_speaking IN ('comecando','em_construcao','confortavel','confiante')),
  nivel_listening TEXT CHECK (nivel_listening IN ('comecando','em_construcao','confortavel','confiante')),
  nivel_vocabulary TEXT CHECK (nivel_vocabulary IN ('comecando','em_construcao','confortavel','confiante')),
  nivel_grammar TEXT CHECK (nivel_grammar IN ('comecando','em_construcao','confortavel','confiante')),
  nivel_pronunciation TEXT CHECK (nivel_pronunciation IN ('comecando','em_construcao','confortavel','confiante')),
  nivel_confianca TEXT CHECK (nivel_confianca IN ('comecando','em_construcao','confortavel','confiante')),
  is_conquista BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own feedbacks or admins can view all"
ON public.feedbacks FOR SELECT TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can create their own feedbacks or admins can create any"
ON public.feedbacks FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can update their own feedbacks or admins can update any"
ON public.feedbacks FOR UPDATE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can delete their own feedbacks or admins can delete any"
ON public.feedbacks FOR DELETE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER update_feedbacks_updated_at
  BEFORE UPDATE ON public.feedbacks
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_feedbacks_student_id ON public.feedbacks(student_id);
CREATE INDEX IF NOT EXISTS idx_feedbacks_user_id ON public.feedbacks(user_id);
CREATE INDEX IF NOT EXISTS idx_feedbacks_ciclo_id ON public.feedbacks(ciclo_id);
CREATE INDEX IF NOT EXISTS idx_feedbacks_conquista ON public.feedbacks(student_id, is_conquista);
