-- ============================================================
-- Speak&Go Evolution Method — Prioridade 2
-- Weekly Planner (vinculado ao Ciclo) + Session Notes (estende class_history)
-- NÃO quebra dados existentes: apenas ADD COLUMN nullable e nova tabela.
-- ============================================================

-- ---------- Tabela: weekly_planner ----------
CREATE TABLE IF NOT EXISTS public.weekly_planner (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ciclo_id BIGINT NOT NULL REFERENCES public.ciclos(id) ON DELETE CASCADE,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  semana INTEGER NOT NULL DEFAULT 1 CHECK (semana BETWEEN 1 AND 8),
  objetivo TEXT,
  missao TEXT,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'concluida')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (ciclo_id, semana)
);

ALTER TABLE public.weekly_planner ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own weekly_planner or admins can view all"
ON public.weekly_planner FOR SELECT TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can create their own weekly_planner or admins can create any"
ON public.weekly_planner FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can update their own weekly_planner or admins can update any"
ON public.weekly_planner FOR UPDATE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can delete their own weekly_planner or admins can delete any"
ON public.weekly_planner FOR DELETE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER update_weekly_planner_updated_at
  BEFORE UPDATE ON public.weekly_planner
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_weekly_planner_ciclo_id ON public.weekly_planner(ciclo_id);
CREATE INDEX IF NOT EXISTS idx_weekly_planner_user_id ON public.weekly_planner(user_id);

-- ---------- Session Notes: estende class_history ----------
-- 'topic' (existente) = tema; 'notes' (existente) mantém-se para notas gerais.
ALTER TABLE public.class_history
  ADD COLUMN IF NOT EXISTS contexto TEXT,
  ADD COLUMN IF NOT EXISTS vocabulario TEXT,
  ADD COLUMN IF NOT EXISTS pontos_atencao TEXT,
  ADD COLUMN IF NOT EXISTS missao_pos_aula TEXT,
  ADD COLUMN IF NOT EXISTS weekly_planner_id BIGINT REFERENCES public.weekly_planner(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_class_history_weekly_planner_id ON public.class_history(weekly_planner_id);
CREATE INDEX IF NOT EXISTS idx_class_history_class_date ON public.class_history(class_date);

-- Nota sobre status de class_history (sem CHECK, mantém compatibilidade):
--   'scheduled'  = Agendada
--   'completed'  = Concluída (valor legado já usado)
--   'rescheduled'= Remarcada
--   'cancelled'  = Cancelada (legado)
--   'report'     = relatório pedagógico legado (não aparece no Quadro de Aulas)
