-- ============================================================
-- Speak&Go Evolution Method — Prioridade 3
-- Biblioteca de Conteúdo (conteudos) + anexo de material em class_history
-- Biblioteca COMPARTILHADA: todos os professores autenticados leem;
-- escrita apenas pelo dono ou admin.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.conteudos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  tema TEXT,          -- viagem, trabalho, entrevista, rotina, etc. (texto livre)
  tipo TEXT NOT NULL DEFAULT 'prompt'
        CHECK (tipo IN ('warm-up', 'prompt', 'listening', 'vocabulario', 'outro')),
  nivel TEXT NOT NULL DEFAULT 'Todos'
        CHECK (nivel IN ('Iniciante', 'Intermediário', 'Avançado', 'Todos')),
  descricao TEXT,
  link TEXT,          -- URL do material (link ou arquivo)
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.conteudos ENABLE ROW LEVEL SECURITY;

-- Leitura: biblioteca compartilhada entre todos os professores autenticados.
CREATE POLICY "Authenticated can view content library"
ON public.conteudos FOR SELECT TO authenticated
USING (true);

-- Escrita: apenas dono ou admin.
CREATE POLICY "Users can create their own content or admins can create any"
ON public.conteudos FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can update their own content or admins can update any"
ON public.conteudos FOR UPDATE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE POLICY "Users can delete their own content or admins can delete any"
ON public.conteudos FOR DELETE TO authenticated
USING (auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'::app_role));

CREATE TRIGGER update_conteudos_updated_at
  BEFORE UPDATE ON public.conteudos
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_conteudos_user_id ON public.conteudos(user_id);
CREATE INDEX IF NOT EXISTS idx_conteudos_tipo ON public.conteudos(tipo);
CREATE INDEX IF NOT EXISTS idx_conteudos_nivel ON public.conteudos(nivel);

-- Anexo de material (referência opcional) numa aula.
ALTER TABLE public.class_history
  ADD COLUMN IF NOT EXISTS conteudo_id BIGINT REFERENCES public.conteudos(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_class_history_conteudo_id ON public.class_history(conteudo_id);
